version: "3.9"

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: "no"
    ports:
      - 8080:8080

volumes:
  db_mysql8_data: {}
