version: '3.3'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306

  adminer:
    image: dockette/adminer:full-php5
    container_name: adminer
    restart: always
    ports:
      - 8080:80