services:
  db:
    image: postgres:17.5-alpine3.21
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - n8n_network

  web:
    image: adminer:5.2.1
    restart: always
    ports:
      - "127.0.0.1:5050:8080"
    depends_on:
      - db
    networks:
      - n8n_network

networks:
  n8n_network:
    external: true

volumes:
  pg_data:
