version: '3.8'

services:
  php-unit-web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    networks:
      - php-network
    command: ["web"]

  php-cli:
    build: .
    volumes:
      - ./app:/var/www/html
    networks:
      - php-network
    profiles:
      - cli
    command: ["bash"]
    tty: true
    stdin_open: true

networks:
  php-network:
    driver: bridge

volumes:
  app_data:
