services:
  redis:
    image: valkey/valkey:8.1.2-alpine
    restart: "always"
    volumes:
      - ./data:/data
    ports:
      - "6379:6379"

  commander:
    image: redis/redisinsight
    restart: "always"
    ports:
      - "127.0.0.1:5540:5540"
