services:
  redis:
    image: valkey/valkey:8.1.2-alpine
    restart: "always"
    volumes:
      - ./data:/data
    ports:
      - "6379:6379"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    user: redis
