services:
  teleport:
    image: public.ecr.aws/gravitational/teleport:${TELEPORT_VERSION}
    restart: always
    volumes:
      - ~/teleport/config:/etc/teleport
      - ~/teleport/data:/var/lib/teleport
    env_file:
      - .env
    ports:
      - 3023:3023
      - 3024:3024
      - 3025:3025
      - 3080:3080
    dns:
      - 1.1.1.1
      - 1.0.0.1
      - 8.8.8.8
      - 8.8.4.4
