version: "3.9"

services:
  teleport:
    image: public.ecr.aws/gravitational/teleport:12.1.1
    restart: always
    volumes:
      - ~/teleport/config:/etc/teleport
      - ~/teleport/data:/var/lib/teleport
    ports:
      - 3023:3023
      - 3025:3025
      - 3080:3080
