version: v3
teleport:
  nodename: pam.premiumfast.net
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  public_addr: pam.premiumfast.net:3025
  proxy_listener_mode: separate
ssh_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3022
  commands:
    - name: hostname
      command: [hostname]
      period: 1m0s
proxy_service:
  enabled: "yes"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
  public_addr: pam.premiumfast.net:443
  listen_addr: 0.0.0.0:3023
  ssh_public_addr: pam.premiumfast.net:3023
  tunnel_listen_addr: 0.0.0.0:3024
  tunnel_public_addr: pam.premiumfast.net:3024