version: "3.9"

services:
  db:
    image: mongo
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
