version: "3.8"
services:
  app:
    build: ./images/php/8.4
    environment:
      # PHP-FPM Pool Configuration
      - FPM_PM=dynamic
      - FPM_PM_MAX_CHILDREN=50
      - FPM_PM_START_SERVERS=5
      - FPM_PM_MIN_SPARE_SERVERS=5
      - FPM_PM_MAX_SPARE_SERVERS=35
      - FPM_PM_MAX_REQUESTS=1000
      - FPM_REQUEST_TIMEOUT=300
      - FPM_LISTEN_TYPE=port # or "socket"

      # PHP Configuration
      - PHP_MEMORY_LIMIT=512M
      - PHP_UPLOAD_MAX_FILESIZE=50M
      - PHP_POST_MAX_SIZE=50M
      - PHP_MAX_EXECUTION_TIME=300

      # Extensions
      - PHP_EXTENSION_REDIS=1
      - PHP_EXTENSION_APCU=1
    volumes:
      - ./app:/application
    ports:
      - "8080:80"
