version: "3"

services:
  uptime:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    restart: always
    volumes:
      - uptime_kuma:/app/data
    ports:
      - "127.0.0.1:3001:3001"

volumes:
  uptime_kuma:
