services:
  uptime:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:${UPTIMEKUMA_VERSION}
    restart: on-failure
    volumes:
      - ~/uptime/data:/app/data
    dns:
      - 1.1.1.1
      - 1.0.0.1
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "127.0.0.1:3001:3001"

networks:
  ip6net:
    enable_ipv6: true
    ipam:
      config:
        - subnet: ${IPV6_SUBNET}