services:
  db:
    image: mariadb:11.4
    restart: "no"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: MyN3wO445w0rd
      MARIADB_DATABASE: pfnapp
      MARIADB_USER: pfnapp
      MARIADB_PASSWORD: MyN3wO445w0rd
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - db_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=1024M
    restart: "no"
    ports:
      - "127.0.0.1:8888:80"
    networks:
      - db_network

networks:
  db_network:
    driver: bridge
